# Makefile for the Sunrise IDE driver for Nextor 3.
#
# By default builds four ROMs (combining this driver with the Nextor
# kernel base file pointed at by NEXTOR_BASE), placed in `bin/`:
#
#   * bin/Nextor-<ver>.SunriseIDE.ROM                     - master + slave
#   * bin/Nextor-<ver>.SunriseIDE.MasterOnly.ROM          - master only
#   * bin/Nextor-<ver>.SunriseIDE.blueMSX.ROM             - blueMSX emulator variant
#   * bin/Nextor-<ver>.SunriseIDE.MasterOnly.blueMSX.ROM  - master only, blueMSX
#
# Intermediate build artifacts (.bin files produced by N80, the
# 256-byte zero block, the temporary padded blueMSX driver images) go
# to `tmp/` instead and are dropped by `make clean`. The shippable
# ROMs in `bin/` survive `make clean` and are removed only by
# `make clean-bin` (or `make distclean` for both).
#
# <ver> is read from the SDK's nextor-kernel-version.txt (the authoritative
# kernel version, generated by the Nextor kernel Makefile from its version
# constants). Any variant suffix (e.g. ".NO_UNDOC.SHIFT_INV") is taken from the
# NEXTOR_BASE filename, which is expected to follow either the repository
# convention Nextor-<ver>.base[<suffix>].dat or the Docker image convention
# kernel_base[<suffix>].dat; a non-standard filename just yields no variant
# suffix.
#
# To build inside the Nextor dev Docker image instead of with a local
# toolchain, use the docker-build.sh wrapper (see README): the image provides
# N80, mknexrom, the SDK and the kernel base files, presetting NEXTOR_BASE and
# NEXTOR_SDK so this Makefile needs no extra configuration. To build against
# every kernel base variant in a directory (one `make` per base file), use
# build-all.sh, locally or via `docker-build.sh --variant all`.


### Configurable variables ###################################################

# NEXTOR_BASE: path to the Nextor kernel base .dat file (mandatory for
# every target except `setup` and the clean ones).
ifeq ($(strip $(NEXTOR_BASE)),)
ifeq ($(filter setup clean clean-bin distclean,$(MAKECMDGOALS)),)
$(error NEXTOR_BASE is not set. Point it at a Nextor kernel base .dat file)
endif
else
ifeq ($(wildcard $(NEXTOR_BASE)),)
$(error NEXTOR_BASE points at '$(NEXTOR_BASE)' which does not exist)
endif
endif

# NEXTOR_SDK: path to the Nextor SDK directory (the one containing 'asm/').
# Defaults to the bundled git submodule.
NEXTOR_SDK ?= external/Nextor/sdk

# Tool overrides. Default to invoking the executables from PATH.
N80      ?= N80
MKNEXROM ?= mknexrom

# NO_UNDOC_CPU_INSTRUCTIONS: when non-empty (e.g. =1) the driver is assembled
# with undocumented Z80 opcodes (those operating on ixh/ixl/iyh/iyl) replaced
# with documented equivalents, for compatibility with Z180-based MSX machines.
# It is inferred from the NEXTOR_BASE filename (see "Build flag inference"
# below): set when the base file's variant suffix contains NO_UNDOC, unset
# otherwise, so the driver always matches the kernel it is combined with. An
# explicit value (environment or command line, even an empty one) overrides
# the inference.


### Output directories #######################################################

BIN := bin
TMP := tmp


### Filename derivation ######################################################

# The kernel version for the ROM names comes from the SDK (authoritative):
# nextor-kernel-version.txt is generated by the Nextor kernel Makefile from
# its version constants, so the name always matches the kernel the SDK targets.
_VERSION_FILE         := $(NEXTOR_SDK)/nextor-kernel-version.txt
NEXTOR_KERNEL_VERSION := $(strip $(shell cat $(_VERSION_FILE) 2>/dev/null))

ifeq ($(NEXTOR_KERNEL_VERSION),)
ifeq ($(filter setup clean clean-bin distclean,$(MAKECMDGOALS)),)
$(error Could not read $(_VERSION_FILE). Is the Nextor SDK submodule initialized and up to date? Run 'make setup')
endif
endif

# The variant suffix (e.g. '.NO_UNDOC.SHIFT_INV') is a property of the base
# file, so it is taken from the NEXTOR_BASE filename. Two naming conventions
# are recognized, both carrying the suffix right after a 'base' token:
#   * the repository convention      'Nextor-<ver>.base[<suffix>].dat'
#   * the Docker image convention    'kernel_base[<suffix>].dat'
# A suffix is present only when 'base' is followed by a '.', so a plain
# '...base.dat' (or any non-standard filename) yields no variant suffix.
_BASE_NAME := $(notdir $(NEXTOR_BASE))
_BASE_STEM := $(_BASE_NAME:.dat=)
ifeq ($(findstring base.,$(_BASE_STEM)),base.)
_VARIANT := .$(lastword $(subst base., ,$(_BASE_STEM)))
else
_VARIANT :=
endif

### Build flag inference #####################################################

# The undoc-free kernel bases carry NO_UNDOC in their variant suffix, so unless
# the flag was given explicitly (`origin` is 'undefined' only when it was not
# set anywhere, and a deliberate empty value counts as set), derive it from
# the suffix. A base file with a non-standard name yields no suffix, hence no
# inference: set the flag by hand in that case.
ifeq ($(origin NO_UNDOC_CPU_INSTRUCTIONS),undefined)
NO_UNDOC_CPU_INSTRUCTIONS := $(if $(findstring NO_UNDOC,$(_VARIANT)),1,)
endif


### ROM names ################################################################

_DRIVER_PREFIX := Nextor-$(NEXTOR_KERNEL_VERSION).SunriseIDE

ROM_REGULAR            := $(BIN)/$(_DRIVER_PREFIX)$(_VARIANT).ROM
ROM_MASTERONLY         := $(BIN)/$(_DRIVER_PREFIX).MasterOnly$(_VARIANT).ROM
ROM_BLUEMSX            := $(BIN)/$(_DRIVER_PREFIX).blueMSX$(_VARIANT).ROM
ROM_MASTERONLY_BLUEMSX := $(BIN)/$(_DRIVER_PREFIX).MasterOnly.blueMSX$(_VARIANT).ROM


### Assembly flags ###########################################################

N80_FLAGS := --no-string-escapes --no-show-banner --verbosity 0 \
             --build-type abs --output-file-extension bin \
             --output-file-case lower \
             --include-directory $(NEXTOR_SDK)

_DEFINES_NO_UNDOC := $(if $(NO_UNDOC_CPU_INSTRUCTIONS),--define-symbols NO_UNDOC_CPU_INSTRUCTIONS)


### Build-flag tracking ######################################################

# The NO_UNDOC setting changes how the driver is assembled but appears in no
# source file, so make can't see it change between runs. Record it in a stamp
# file that the intermediate .bin targets depend on: switching
# NO_UNDOC_CPU_INSTRUCTIONS then forces a reassembly instead of silently
# combining a mismatched (e.g. non-undoc) driver with a .NO_UNDOC kernel base.
_BUILD_ID    := undoc=$(if $(NO_UNDOC_CPU_INSTRUCTIONS),1,0)
_BUILD_STAMP := $(TMP)/.build-id

# Rewrite the stamp only when the id actually changes, so its mtime (and hence
# the rebuild) is triggered only on a real flag change. FORCE makes the recipe
# run every build to perform the check.
$(_BUILD_STAMP): FORCE | $(TMP)
	@printf '%s\n' '$(_BUILD_ID)' | cmp -s - $@ || printf '%s\n' '$(_BUILD_ID)' > $@


### Default target ###########################################################

# Set explicitly: the build-flag stamp rule above is the first target in the
# file, so without this `make` with no arguments would build only the stamp.
.DEFAULT_GOAL := all

.PHONY: all clean clean-bin distclean FORCE
all: $(ROM_REGULAR) $(ROM_MASTERONLY) $(ROM_BLUEMSX) $(ROM_MASTERONLY_BLUEMSX)

FORCE:

# Order-only prereqs for outputs that live in the build directories:
# ensure the directory exists without making its mtime affect rebuild
# decisions.
$(BIN) $(TMP):
	@mkdir -p $@


### Driver and chgbnk binaries (intermediates) ###############################

# 'driver.asm' produces the hardware driver. N80's "if the output path
# is a directory, use the default base name in it" behavior lets us
# point it at $(TMP)/ for the regular variants.

$(TMP)/driver.bin: driver.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) driver.asm $(TMP)/ $(N80_FLAGS) $(_DEFINES_NO_UNDOC)

$(TMP)/driver.masteronly.bin: driver.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) driver.asm $(TMP)/driver.masteronly.bin $(N80_FLAGS) $(_DEFINES_NO_UNDOC) --define-symbols MASTER_ONLY

# 'driver-bluemsx.asm' is the variant used inside the blueMSX emulator.

$(TMP)/driver-bluemsx.bin: driver-bluemsx.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) driver-bluemsx.asm $(TMP)/ $(N80_FLAGS) $(_DEFINES_NO_UNDOC)

$(TMP)/driver-bluemsx.masteronly.bin: driver-bluemsx.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) driver-bluemsx.asm $(TMP)/driver-bluemsx.masteronly.bin $(N80_FLAGS) $(_DEFINES_NO_UNDOC) --define-symbols MASTER_ONLY

$(TMP)/chgbnk.bin: chgbnk.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) chgbnk.asm $(TMP)/ $(N80_FLAGS) $(_DEFINES_NO_UNDOC)


### ROM combination via mknexrom (final outputs) #############################

$(ROM_REGULAR): $(TMP)/driver.bin $(TMP)/chgbnk.bin | $(BIN)
	$(MKNEXROM) $(NEXTOR_BASE) $@ /d:$(TMP)/driver.bin /m:$(TMP)/chgbnk.bin

$(ROM_MASTERONLY): $(TMP)/driver.masteronly.bin $(TMP)/chgbnk.bin | $(BIN)
	$(MKNEXROM) $(NEXTOR_BASE) $@ /d:$(TMP)/driver.masteronly.bin /m:$(TMP)/chgbnk.bin

# The blueMSX-targeted ROMs need a 256-byte zero block prepended to the
# driver binary before mknexrom combines it with the kernel.

$(TMP)/256.bytes: | $(TMP)
	dd if=/dev/zero of=$@ bs=1 count=256

$(ROM_BLUEMSX): $(TMP)/driver-bluemsx.bin $(TMP)/chgbnk.bin $(TMP)/256.bytes | $(BIN)
	cat $(TMP)/256.bytes $(TMP)/driver-bluemsx.bin > $(TMP)/_driver-bluemsx.padded.bin
	$(MKNEXROM) $(NEXTOR_BASE) $@ /d:$(TMP)/_driver-bluemsx.padded.bin /m:$(TMP)/chgbnk.bin
	rm -f $(TMP)/_driver-bluemsx.padded.bin

$(ROM_MASTERONLY_BLUEMSX): $(TMP)/driver-bluemsx.masteronly.bin $(TMP)/chgbnk.bin $(TMP)/256.bytes | $(BIN)
	cat $(TMP)/256.bytes $(TMP)/driver-bluemsx.masteronly.bin > $(TMP)/_driver-bluemsx-masteronly.padded.bin
	$(MKNEXROM) $(NEXTOR_BASE) $@ /d:$(TMP)/_driver-bluemsx-masteronly.padded.bin /m:$(TMP)/chgbnk.bin
	rm -f $(TMP)/_driver-bluemsx-masteronly.padded.bin


### Housekeeping #############################################################

# `make clean` keeps the shippable ROMs in bin/, only wipes intermediates.
clean:
	rm -rf $(TMP)

# `make clean-bin` removes the shippable ROMs.
clean-bin:
	rm -rf $(BIN)

# `make distclean` removes both.
distclean: clean clean-bin


### One-time setup ###########################################################

# `make setup` initializes the Nextor SDK submodule as a blobless
# partial clone with sparse-checkout for the `sdk/` directory only, so
# that the full Nextor repository is never fetched. Run this once,
# right after cloning this repo, to initialize the external/Nextor directory.
.PHONY: setup
setup:
	@echo "Setting up the Nextor SDK submodule (blobless + sparse-checkout for sdk/ only)..."
	git submodule init external/Nextor
	git submodule update --init --filter=blob:none external/Nextor
	git -C external/Nextor sparse-checkout init --cone
	git -C external/Nextor sparse-checkout set sdk
	git -C external/Nextor checkout
	@echo "Done. Set NEXTOR_BASE and run 'make' to build."
